version: '3.8'

services:
  yt-dlp-host:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        YT_DLP_VERSION: latest
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads 
      - ./yt_dlp_app.db:/app/yt_dlp_app.db
    environment:
      # SQLALCHEMY_DATABASE_URL: "sqlite+aiosqlite:///./my_custom_db_name.db"
      # INITIAL_ADMIN_KEY_VALUE: "supersecretadminkey"
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
