services:
  yt-dlp-host:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./downloads:/app/downloads
      - ./jsons:/app/jsons
      - ./config.py:/app/config.py
    environment:
      - FLASK_APP=src.server:app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    restart: unless-stopped
