services:
  yt-dlp-host:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./jsons:/app/jsons
      - ./config.py:/app/config.py
    environment:
      - FLASK_APP=src.server:app
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
